### ISSUE TITLE
No data in demo page with changed ports and port forwarding via SSH

### ISSUE THREAD

**Issue by archenroot** [rapidsai/cuxfilter#1]
I followed all instructions, I downloaded data set and map to the docker container, following ls from container:
```
root@a909fae45a85:/usr/src/app# ls -la /usr/src/app/node_server/uploads
total 3578988
drwxrwxr-x 2 1000 1000       4096 Dec 27 07:19 .
drwxrwxr-x 1 root root       4096 Dec 27 07:23 ..
-rw-rw-r-- 1 1000 1000 3664867524 Nov 29 17:22 146M_predictions_v2.arrow

```

So data are there, but when I open http://localhost:43004/demos/examples/demo1.html (note I SSH forward 3004 port from server to laptop), I got this page:
![image](https://user-images.githubusercontent.com/553512/50470850-b3bc8b80-09cb-11e9-9af0-4f16f9070ab2.png)

I think its just something related to data upload, or maybe mistake on my side... maybe it will be good to add some kind of logging.

**Comment by archenroot** [comment]
Ok, I see in Chromium dev console:
```
demo1.html:91 undefined
:3000/cuXfilter:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
demo1.html:1 Uncaught (in promise) TypeError: Failed to fetch
```

So looks like issue with port forwarding, etc.

**Comment by archenroot** [comment]
Ok, so when I put back the ports to 300* range (not 40000 range as I wanted), I am able to access the system and it shows me graphs:
![image](https://user-images.githubusercontent.com/553512/50473500-97721c00-09d6-11e9-9524-c115e7a90c85.png)


So maybe the port range 300* is enforced somewhere.... 

So this works, but the CTG sample doesn't work, it blinks for about half second so I am able to see layout (the data are empty), but than just black screen appear:
![image](https://user-images.githubusercontent.com/553512/50473569-ddc77b00-09d6-11e9-8951-b93da72037b3.png)

I will close this and report new issue.

**Comment by archenroot** [comment]
I decided to reopen it, in general I am interested 
- in running the solution on other than different ports
- support port forwarding port where mapping is between different ports

It looks there is something enforced and when I switch to other ports, its trying to use default ones...

**Comment by archenroot** [comment]
Got to testing again...

**Comment by archenroot** [comment]
When running on standard ports (300*) I can connect to /demos, just one failure in console:
```
demo1.html:184 Uncaught ReferenceError: dimension1 is not defined
    at updateBins (demo1.html:184)
    at HTMLInputElement.oninput (demo1.html:56)
```

**Comment by exactlyallan** [comment]
@archenroot Did you manage to figure out the issue? Also, regarding the blank screen on the GTC demo, could you share any error logs in the browser dev console? Thanks.
