### ISSUE TITLE
/demo/examples throwing 500 with {"error":"err"}

### ISSUE THREAD

**Issue by 1TommyCheung** [rapidsai/cuxfilter#10]
Hi there,

I managed to build the container deployed it on a remote server with it's ip_server address configured.  demo/examples & GTC_Demo throws the error message at the subject.  In Jupyter it seems to be working as I am getting bar charts and graphs from the dataset.  Anyway what's happening here?

Thanks,
Tommy

**Comment by exactlyallan** [comment]
I believe the latest update could resolve this issue - correct me if I'm wrong @AjayThorve

**Comment by AjayThorve** [comment]
Yep, the latest PR resolves this specific issue
