### ISSUE TITLE
[BUG] deckgl.charopleth3d will not render the chart if data column name is not uppercase

### ISSUE THREAD

**Issue by ivanajovicic** [rapidsai/cuxfilter#102]
**Describe the bug**
When trying to use `deckgl.charopleth3d` , it seems that the name of the column in the dataframe somehow influences if the data gets rendered at all. As far as I can tell from experimentation, column names that are uppercase work for some reason. 

**Steps/Code to reproduce bug**
```
import cudf
import numpy as np
import cuxfilter

geoJSONSource ='https://raw.githubusercontent.com/rapidsai/cuxfilter/GTC-2018-mortgage-visualization/javascript/demos/GTC%20demo/src/data/zip3-ms-rhs-lessprops.json'

size = 1000

color=np.random.randint(50,100, size=size)
zip_fake = np.random.randint(1,50, size = size)
y = np.random.randint(5000,70000, size=size)
df = cudf.DataFrame( {'Zip': zip_fake,
                      'color':color,
                    'elevation': y})
cux_df = cuxfilter.DataFrame.from_dataframe(df)

cux_df.data['Zip'].astype('float64')
cux_df.data['elevation'].astype('float64')
cux_df.data['color'].astype('float64')

chart0 = cuxfilter.charts.deckgl.choropleth3d( x='Zip', color_column='color', color_aggregate_fn='mean', elevation_column='elevation', elevation_factor=1, elevation_aggregate_fn='sum',  geoJSONSource=geoJSONSource, data_points=size
)

#declare dashboard
d = cux_df.dashboard([chart0],theme = cuxfilter.themes.light, title='test dashboard')

d.app(notebook_url='')
```

**Expected behavior**
Chart should be rendered for any column name given the same data.

**Environment details (please complete the following information):**
 - Environment location:  Docker
 - Method of cuxfilter install: Docker 
 

`docker pull rapidsai/rapidsai:cuda10.1-runtime-ubuntu18.04`
 `docker run --runtime=nvidia -it -v ~/workdir:/mnt -p 8888:8888 rapidsai/rapidsai:cuda10.1-runtime-ubuntu18.04`

 

**Additional context**

**Comment by AjayThorve** [comment]
this is fixed now, should be available in nightlys(>=0.13) until the official release
