### ISSUE TITLE
[FEA] Guidance on how to use cuxfilter in colab

### ISSUE THREAD

**Issue by zouhx11** [rapidsai/cuxfilter#103]
I wish I could use cuxfilter for visualization in google colab, a bash file will be very helpful.

**Comment by AjayThorve** [comment]
Hey @zouhx11 , so cuxfilter uses bokeh server for interactions between python and front-end js charts, which actually uses Comms, which is not completely supported in collab. So as of now this won't work.

You can track this issues on collab tools for more information -> https://github.com/googlecolab/colabtools/issues/217

**Comment by zouhx11** [comment]
Thanks, @AjayThorve , I'll keep an eye on this.
