### ISSUE TITLE
[BUG] "no module named cuxfilter" error when importing cuXfilter

### ISSUE THREAD

**Issue by rnyak** [rapidsai/cuxfilter#105]
**Describe the bug**

I am getting   `no module named cuxfilter` when I run `import cuxfilter` within rapids docker container (0.13 release). Same error for the `import datashader`. Note that cuXfilter works fine in the rapids docker 0.12 release. 

I am using docker + examples (non dev environment )
.
**Steps/Code to reproduce bug**

**Expected behavior**

`import cuxfilter`  and `import datashader` should work without generating any error.

**Environment details (please complete the following information):**
 - Environment location: [Docker 0.13 release )]
 - Method of cuxfilter install: [Docker]
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

 `docker pull rapidsai/rapidsai-nightly:cuda10.1-runtime-ubuntu16.04`

**Comment by AjayThorve** [comment]
As per @dillon-cullinan , cuxfilter isn't in the rapids meta package, it requires system libraries that we don't have conda package equivalents of yet. This stuff is still a WIP

**Comment by raviy0807** [comment]
@AjayThorve , but the README and docker image says that it has cuxfilter in it.

I also tried to use runtime image and didn't find cuxfilter's method.

**Comment by jakirkham** [comment]
@AjayThorve , what dependencies are we missing?

**Comment by AjayThorve** [comment]
@jakirkham  some system level packages -> https://github.com/rapidsai/cuxfilter#troubleshooting

**Comment by jakirkham** [comment]
Ah ok. So mostly a bunch of X11 stuff, is that right?

There are some X11 packages in conda-forge. Could try those. One question that has come up before is how well tested they are from a performance perspective. So it might be worth comparing them to system provided X11 packages to see if you note any difference.

**Comment by AjayThorve** [comment]
This should be resolved now with a stable 0.13 release. @rnyak and @raviy0807 , feel free to reopen the issue if it still occurs
