### ISSUE TITLE
[BUG] Error when installing cuXfilter from source.

### ISSUE THREAD

**Issue by rnyak** [rapidsai/cuxfilter#107]
**Describe the bug**
I am following the instructions to build cuXfilter from source. I get the following error when I update conda env using `cuxfilter_dev_cuda10.1.yml`:

ERROR:
```
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - cudf[version='>=0.13']
```

**Steps/Code to reproduce bug**

1. Clone the repository and submodules
```
CUXFILTER_HOME=$(pwd)/cuxfilter
git clone https://github.com/rapidsai/cuxfilter.git $CUXFILTER_HOME
cd $CUXFILTER_HOME
```
```
2. conda create --name cuxfilter_dev 
```
```
3.  conda activate cuxfilter_dev 
```
4. install cudf via 
```
conda install -c rapidsai-nightly -c nvidia -c conda-forge \
    -c defaults cudf=0.13 python=3.7 cudatoolkit=10.1
```
5.  Update conda env
```
conda env update --file conda/environments/cuxfilter_dev_cuda10.1.yml
```
That step generates the error above.

**Expected behavior**

`rapidsai-nightly` is missing in the channel list in `cuxfilter_dev_cuda10.1.yml`,  and `name` does not match with the env name- cuxfilter_dev. But even though I perform these updates, I still get the same error.

We should install cuXfilter from source without any issue.

**Environment details (please complete the following information):**
 - Environment location: [conda]
 - Method of cuxfilter install: [from source]
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used
 

**Additional context**

**Comment by rnyak** [comment]
@AjayThorve was that issue solved? Thanks.

**Comment by AjayThorve** [comment]
@rnyak PR #109 fixes this, should be merged in a few minutes.
