### ISSUE TITLE
GTC demo using GPUs not working

### ISSUE THREAD

**Issue by lmichelaltair** [rapidsai/cuxfilter#12]
Dear developers,

I encounter problems rendering on the GPU engine running the GTC demo example.
The hard/software components are the following: DGX-1 with V100-32GB on OS 4.0.5 (Ubuntu 18.04.2 LTS). The V100 run driver version 410.104. The CUDA-Version is 10.0. The system was idle during my tests, so there should not be any memory issues.

While the test-file seems to get loaded correctly (it displays the number of aggregated mortgages), when trying to render with the GPU engine, I cannot get any visualization out of the webinterface, even though I already waited for more than an hour in the screenshot-state to get some:
![rendering_gpu](https://user-images.githubusercontent.com/51695334/59251420-11ffc280-8c2a-11e9-8f85-3579164017dd.PNG)

If I switch to the CPU engine everything works fine within about 60 seconds:
![rendering_cpu-1](https://user-images.githubusercontent.com/51695334/59251443-1c21c100-8c2a-11e9-899d-6f8c1f383aa0.PNG)

I built and ran the docker-container for cuxfilter with a few configuration and the loaded dataset. I am actually doing this with

`docker build -t lmichel-viz .`
`docker run --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=0,1 -p 80:80 --env-file ./config.env -v /local/disk/data:/usr/src/app/node_server/uploads --rm -d lmichel-viz`

The config.env-File still has the contents of the original one (https://github.com/rapidsai/cuxfilter/blob/master/config.env). I only changed the server-ip to localhost and added my mapbox-token, which should not make any difference for my problem.

Do you have any idea how to solve this problem? If you need any additional information, please let me know.

Thanks,
Linus

**Comment by exactlyallan** [comment]
Thanks for the detailed issue - If you open the browser web developer tools and share any logged errors, it might give us a better indication of where communication issue is happening.

**Comment by AjayThorve** [comment]
Also, can you try replacing the first 2 lines of Dockerfile with the correct cuda and ubuntu version.

**Comment by lmichelaltair** [comment]
> Thanks for the detailed issue - If you open the browser web developer tools and share any logged errors, it might give us a better indication of where communication issue is happening.

Thank you for the quick reply! I already looked into that, but could not determine any obvious communication issue. The outputs were generated with the default Dockerfile (CUDA 9.2, Ubuntu 16.04). During the use of the GPU engine, the console finalizes in this state:
![console_GPU_CUDA9 2_Ubuntu16 04](https://user-images.githubusercontent.com/51695334/59330459-cdd7f500-8cf1-11e9-825c-35f2d814d5ba.PNG)

After switching to the CPU engine, it fills up like the following (the red line at top marks the end of the console-output belonging to the GPU engine before):
![console_CPU_CUDA9 2_Ubuntu16 04](https://user-images.githubusercontent.com/51695334/59330472-d6c8c680-8cf1-11e9-8534-15ed848225d0.PNG)

I also looked into `docker logs` which may give a good hint:
[docker_logs_1604.log](https://github.com/rapidsai/cuxfilter/files/3280094/docker_logs_1604.log)
Unfortunately, executing `conda install cudatoolkit` does not change anything, even after stopping and starting the container again (without a --rm flag for the docker run command).


> Also, can you try replacing the first 2 lines of Dockerfile with the correct cuda and ubuntu version, and then building the container?

Thanks, I tried that as well, but after setting CUDA to "10.0" and the linux version to "ubuntu18.04" the built container seems not to work properly. Please find attached the build-logs of the default with CUDA 9.2 and Ubuntu 16.04 and the changed one with CUDA 10.0 and Ubuntu 18.04. For me, they don't show an obvious failure:
[build_1604.log](https://github.com/rapidsai/cuxfilter/files/3280101/build_1604.log)
[build_1804.log](https://github.com/rapidsai/cuxfilter/files/3280103/build_1804.log)

When executing the 18.04-container, the browser console shows the following:
[browser_console_1804.log](https://github.com/rapidsai/cuxfilter/files/3280116/browser_console_1804.log)

`docker logs` then shows the following:
[docker_logs_1804.log](https://github.com/rapidsai/cuxfilter/files/3280118/docker_logs_1804.log)

I hope this helps.
Thank you for your help!

**Comment by AjayThorve** [comment]
hey @lmichelaltair, the latest PR which was merged yesterday should solve this issue. Basically was the issue with -> ```Not a directory: '/usr/local/cuda/nvvm/lib64/libnvvm.so'``` in the Dockerfile. The new installation only requires -> ```'/usr/local/cuda/nvvm/lib64/'``` for the environment variable NUMBAPRO_NVVM (see line 7 of the Dockerfile). Let me know if it this fix works!

**Comment by lmichelaltair** [comment]
Hi @AjayThorve,
this new release solves all problems for now. Thanks a lot for your help!
