### ISSUE TITLE
[FEA]Add data shader's "Hover on data point" and ability to add legends

### ISSUE THREAD

**Issue by taureandyernv** [rapidsai/cuxfilter#137]
Currently, datashader has the ability to 
- Hover on data points
- Add legends

They use holoviews for that.  https://datashader.org/getting_started/Interactivity.html.  Hoping that we can do that for some of our smaller datasets, as it would be incredibly useful.  I understand the latency would be far greater if we added metadata for millions of dots, but i'm taking thousands, like clustered points

**Comment by AjayThorve** [comment]
cuxfilter now supports legends for datashader charts. ref #168
