### ISSUE TITLE
[DOC] "Title" parameter missing in example string for Datashader examples

### ISSUE THREAD

**Issue by taureandyernv** [rapidsai/cuxfilter#139]
## Report incorrect documentation

**Location of incorrect documentation**
In our datashader charts section, each section is missing the title parameter in the example code string.  it is there in the parameters section

https://docs.rapids.ai/api/cuxfilter/stable/charts/datashader_charts.html#

This can make some users miss the feature or think that it doesn't exist

**Comment by AjayThorve** [comment]
Fixed in #151
