### ISSUE TITLE
[HELP] How  does Sanic work with localCUDACluster properly?

### ISSUE THREAD

**Issue by wuxianliang** [rapidsai/cuxfilter#14]
I am taking cuxfilter as an example of machine learning Apps and wish to modify the codes to  localCUDACluster. The only example which uses Sanic and Dask  is 
```
from sanic import Sanic
from sanic import response

from tornado.platform.asyncio import BaseAsyncIOLoop, to_asyncio_future
from distributed import LocalCluster, Client


app = Sanic(__name__)


def square(x):
    return x**2


@app.listener('after_server_start')
async def setup(app, loop):
    # configure tornado use asyncio's loop
    ioloop = BaseAsyncIOLoop(loop)

    # init distributed client
    app.client = Client('tcp://localhost:8786', loop=ioloop, start=False)
    await to_asyncio_future(app.client._start())


@app.listener('before_server_stop')
async def stop(app, loop):
    await to_asyncio_future(app.client._shutdown())


@app.route('/<value:int>')
async def test(request, value):
    future = app.client.submit(square, value)
    result = await to_asyncio_future(future._result())
    return response.text(f'The square of {value} is {result}')


if __name__ == '__main__':
    # Distributed cluster should run somewhere else
    with LocalCluster(scheduler_port=8786, nanny=False, n_workers=2,
                      threads_per_worker=1) as cluster:
        app.run(host="0.0.0.0", port=8000)
```
from Sanic wiki.
Sadly, it does not wok if we just use LocalCUDACluster instead of LocalCluster with proper imports. Even the orginal codes does not work anymore. Hardly find any example on LocalCUDACluster and python web frameworks. So is there a plan to upgrade cuxfilter to distributed version? It would be the only example on github. Thank you very much.

**Comment by AjayThorve** [comment]
Hey @wuxianliang, cuxfilter can be used in a distributed manner, by using dask-cudf instead of cudf (https://rapidsai.github.io/projects/cudf/en/0.8.0/dask-cudf.html#). No plans as of now to modify sanic to support the distributed version.  

We are working on a jupyter notebook based version on cuXfilter, and that along with dask-cudf could essentially solve the problem.

**Comment by wuxianliang** [comment]
Thank you for the response. I tried kernel_gateway yesterday, it works well. Jupyter notebook is a nice choice.
