### ISSUE TITLE
[BUG][DOC] Clarify, update, or remove the confusing `add_chart` function

### ISSUE THREAD

**Issue by taureandyernv** [rapidsai/cuxfilter#140]
Was really enjoying cuxfilter, but `add_chart` doesn't function as its name implies and it's frustrating.

To add a chart, you have to create a new chart and then run it, which gives you a new link to view it on - not update your old chart.  The docs does not make its functionality - or usefulness - clear, as you could have done that the standard way of creating a new dashboard, without `add_chart`, and it would have made more sense

can we:
- Clarify useful usecases of `add_chart` in the docs 
- remove `add_chart`, as its usefulness is suspect
 OR 
- make `add_chart` update dashboard dynamically without needing to create a new dashboard.

**Comment by AjayThorve** [comment]
Implemented in #151 - Went ahead with the 3rd option - make add_chart update dashboard dynamically without needing to create a new dashboard.

After add_charts is executed, a simple page refresh for the tab running dashboard would updated(reintialize all charts) the dashboard
