### ISSUE TITLE
[BUG][FEA] Dashboard link auto created in jupyter-lab doesn't load dashboard due to bug

### ISSUE THREAD

**Issue by taureandyernv** [rapidsai/cuxfilter#141]
When you create a dashboard in a remote system, jupyter returns a string of text that contains a link
`d.show(10.***.***.***:8888)`
`Dashboard running at http://10.***.***.***:8888/proxy/51975/`

the http is shown as a clickable link in some versions of jupyter lab.  That is cool and useful...but...
The issue is that that link terminates before the final `/`, so it ends with `proxy/51975` instead of `proxy/51975/`.  Without the final `/` , the chart never loads and upon inspection, shows bokeh errors.  With the `/`, it loads just fine.  However, as it is a link, which you click, and there is no message to cut and paste the complete http string, including the `/`, the experience is broken.  

Can we add a message, a button, or correct the link forming to provide the user the intended experience?

**Comment by AjayThorve** [comment]
cuxfilter now displays a clickable button instead of a link, which redirects to a new browser tab, avoiding the link copy paste effort
