### ISSUE TITLE
[FEA] Add Label_map for datashader plots

### ISSUE THREAD

**Issue by taureandyernv** [rapidsai/cuxfilter#145]
**Is your feature request related to a problem? Please describe.**
I wish cuXfilter would let me label the values of Datashader plots with a different mapping, as it can with the Bokeh plots.  

Example, if i have to use numeric 1 and 0, I'd like to be able to relabel them as `True` and `False`, `Yes` and `No` or `Positive` and `Negative` on the plot.  

The only alternate is explicitly telling the reader to make the mapping in their mind in the notebook or as part of the title and show 1 and 0.

**Comment by AjayThorve** [comment]
Need further clarification on this, can you add a reproducible code. What datashader charts are you aiming for?

**Comment by exactlyallan** [comment]
We do have label maps currently.
