### ISSUE TITLE
[FEA] Add Boolean data type support

### ISSUE THREAD

**Issue by taureandyernv** [rapidsai/cuxfilter#146]
I wish that cuXFilter could bring in Boolean data types direct from the dataframe.

Right now, i have to do `df['bool'] = df['bool']*1` or `df['bool'] = df['bool'].astype('int8')` to convert the column to int, which cuXFilter can read.  When I chart this, instead of having `True` and `False` as the Labels, i get `1` and `0`, which is sub-optimal

**Comment by AjayThorve** [comment]
Implemented in #151 for bar and line charts. Non-aggregate datashader charts support it too.
