### ISSUE TITLE
[FEA] Plot CuPy array support

### ISSUE THREAD

**Issue by gbatmaz** [rapidsai/cuxfilter#149]
**Is your feature request related to a problem? Please describe.**

It'd be really nice to be able to plot CuPy arrays withing RAPIDS, e.g. using CuXfilter without going through multiple types i.e. trying to go from `arrays` to `dataframes` via `dlpack`. 

**Describe the solution you'd like**

It'd be really nice to plot a CuPy array using RAPIDS without conversions.

**Comment by exactlyallan** [comment]
We are somewhat bound to cuDF - however this would be an very useful request for the holoviz folks, especially forhttps://hvplot.holoviz.org/
