### ISSUE TITLE
[DOC] cuXfilter inconsistent naming 

### ISSUE THREAD

**Issue by miguelusque** [rapidsai/cuxfilter#170]
## Report incorrect documentation

**Location of incorrect documentation**
https://docs.rapids.ai/api
https://github.com/rapidsai/cuxfilter/blob/branch-0.15/README.md
https://github.com/rapidsai/cuxfilter/blob/branch-0.15/CHANGELOG.md
https://rapids.ai/

**Describe the problems or issues found in the documentation**
I have noticed that this library is spelled differently in different documents.

I have found written as _cuxfilter_, _cuXfilter_, _cuXFilter_and _CUXFILTER_.

I think a unique form should be used.

**Suggested fix for documentation**
My favourite is _cuXFilter_, but it is just a suggestion.

**Comment by AjayThorve** [comment]
#180 fixes this - changelog and readme can be controlled from this repo, rapids.ai website I think the name is all caps to be consistent with the page theme

**Comment by miguelusque** [comment]
Hi @AjayThorve ,

Thank you for taking care of this issue.

I have performed the following search in RAPIDS repo, and I have found more locations where the spelling is still inconsistent:

> https://github.com/search?q=org%3Arapidsai+cuxfilter&type=Code

Some examples of incorrect spelling (not all of them):

https://github.com/rapidsai/notebooks/blob/branch-0.15/README.md
https://github.com/rapidsai/cuxfilter/blob/branch-0.15/CHANGELOG.md
https://github.com/rapidsai/cuxfilter/blob/branch-0.15/ci/cpu/build.sh

Regards,
Miguel

**Comment by AjayThorve** [comment]
Hey @miguelusque, this got delayed due to other issues which prevented a cuxfilter release, but now that it has released, I've taken care of the consistent naming in the docs, and changelog and readme  files of cuxfilter. 

I'll go through the other repositories which contain inconsistent naming and fix those soon.

**Comment by miguelusque** [comment]
Hi!

It looks this issue can be closed now.

Thank you for taking care of it!

Regards,
Miguel
