### ISSUE TITLE
[BUG]Stacked lines aren't really 'stacked lines', but really 'multi-lines'

### ISSUE THREAD

**Issue by taureandyernv** [rapidsai/cuxfilter#175]
**Describe the bug**
Was looking for a way to stack some time data based and found that the chart "stacked_line" isn't really "stacked lines" but "multi-lines". Stacked lines cannot cross.  Please update docs or update code.

**Steps/Code to reproduce bug**
Download this csv: https://drive.google.com/file/d/1ttJZytQ9fVHV-Cjz5v78OxTVb61OJrMo/view?usp=sharing
and run:
```
import cudf
from cuxfilter.sampledata import signals_data
from cuxfilter import DataFrame
from cuxfilter.charts import stacked_lines
df = cudf.read_csv('two_days.csv')
cux_df = DataFrame.from_dataframe(df)

stacked_lines_chart = stacked_lines(x='day_of_the_month', y = ['0','1'], add_interaction= True, colors = ["red", "black"]

d = cux_df.dashboard([stacked_lines_chart])

stacked_lines_chart.view()
```

``'
![image](https://user-images.githubusercontent.com/46935140/90313263-ff34ed80-debf-11ea-9f5f-61bf8152b959.png)

**Expected behavior**
The lines should be at levels where the values stack upon one another
```
import pandas
import matplotlib.pyplot as plt
f = plt.figure()
df = df.to_pandas()
plt.title('Total NYC Yellow Taxi Rides \n Janurary 2015 by Day and Time', color='black')
df[[0,1]].plot(kind='line', stacked=True, ax=f.gca())
plt.legend(loc='center left', bbox_to_anchor=(1.0, 0.5))
plt.show()
```
and get

![image](https://user-images.githubusercontent.com/46935140/90314060-c0a23180-dec5-11ea-960a-333dd97e9d23.png)

**Environment details (please complete the following information):**
 - Environment location: [Bare-metal]
 - Method of cuxfilter install: [conda]
 

**Additional context**

**Comment by AjayThorve** [comment]
Thanks for the pointing this out @taureandyernv , will rename it to multi-lines for now, and add stacked-line charts in our priority list

**Comment by exactlyallan** [comment]
While accurate, we are using datashader's nomenclature for 'stacking lines' on top of each other. But agreed there is always ambiguity with 'stacked' lines / area charts.

**Comment by taureandyernv** [comment]
@exactlyallan understood.  May we simply note it in the docs to avoid any confusion?
