### ISSUE TITLE
GTC  Sample - Black Screen Only

### ISSUE THREAD

**Issue by archenroot** [rapidsai/cuxfilter#2]
I can display /demo page on port 3004 populated with data, but when accessing http://localhost:3005/ only black screen occurs
![image](https://user-images.githubusercontent.com/553512/50473603-ff286700-09d6-11e9-8859-dbec1870ddcb.png)

**Comment by AjayThorve** [comment]
Can you share any console messages in the chromium toolbar, and the config.json file as well, might be able to help you better in that case

**Comment by archenroot** [comment]
@AjayThorve - sure, I will get to office in few hours... thx for reply

**Comment by archenroot** [comment]
@AjayThorve - ok, its clear now :-) 
```
Error: Use a public access token (pk.*) with Mapbox GL, not a secret access token (sk.*). See https://www.mapbox.com/api-documentation/#access-tokens
    at h (bundle.js:49)
    at bundle.js:49
    at n.loadURL (bundle.js:49)
    at i.setStyle (bundle.js:49)
    at new i (bundle.js:49)
    at t.value (bundle.js:8)
    at t.value (bundle.js:8)
    at new t (bundle.js:8)
    at e.value (bundle.js:61)
    at Da (bundle.js:40)
```
