### ISSUE TITLE
[BUG] timeseries datetime64 not supported - invalid type promotion 

### ISSUE THREAD

**Issue by geoHeil** [rapidsai/cuxfilter#204]
**Describe the bug**
A `datetime64[ns]` type for a timeseries column results in TypeError: invalid type promotion when trying to plot a cuxfilter plot.

**Steps/Code to reproduce bug**

```
import pandas as pd
import cuxfilter
import cudf
from cuxfilter import DataFrame, themes, layouts, charts
from cuxfilter.assets.custom_tiles import get_provider, Vendors

df_minimal = pd.DataFrame({'foo': [1,2,3], 'time':['2020-01-01', '2020-01-10 01', '2020-02-20 22']})
df_minimal['time'] = pd.to_datetime(df_minimal['time'])

cm_cu = cudf.from_pandas(df_minimal)
cux_df = cuxfilter.DataFrame.from_dataframe(cm_cu)

chart2 = charts.line('time')
charts_list = [chart2]

d = cux_df.dashboard(charts_list, title='time series', layout=layouts.feature_and_base, theme=themes.rapids, data_size_widget=True)
```

**Expected behavior**
the datatype should be supported as this is supported by cudf and fundamentally the normal way of handling time also in pandas

**Environment details (please complete the following information):**
 - Environment location: bare metal
 - Method of cuxfilter install: conda, version 0.15

**Comment by geoHeil** [comment]
A workaround obviously is: `df_minimal['time'] = df_minimal['time'].astype('int64')`, but then the formatting of the time series labels is lost - which would be required for semantically useful plots.

**Comment by AjayThorve** [comment]
HI @geoHeil , thanks for the feature request, this seems like a fair request, given that cudf already support pd.datetime. I'll get to it very soon, shall keep you posted on it.
