### ISSUE TITLE
[QST]I‘m tring the demo code and get a problem

### ISSUE THREAD

**Issue by liukai1919** [rapidsai/cuxfilter#213]
**What is your question?**
I m using a RTX 3090 and rapids 0.16 on ubuntu 20.04. its works when I run charts.view(),but when I run the code below:
import cuxfilter

cux_df = cuxfilter.DataFrame.from_arrow('auto_accidents.arrow')
cux_df.data['ST_CASE'] = cux_df.data['ST_CASE'].astype('float64')

label_map = {1: 'Sunday',    2: 'Monday',    3: 'Tuesday',    4: 'Wednesday',   5: 'Thursday',    6: 'Friday',    7: 'Saturday',    9: 'Unknown'}
gtc_demo_red_blue_palette = [ "#3182bd", "#6baed6", "#7b8ed8", "#e26798", "#ff0068" , "#323232" ]

#declare charts
chart1 = cuxfilter.charts.scatter(x='dropoff_x', y='dropoff_y', aggregate_col='DAY_WEEK', aggregate_fn='mean',
                                color_palette=gtc_demo_red_blue_palette, tile_provider='CARTODBPOSITRON',
                                pixel_shade_type='linear')
chart2 = cuxfilter.charts.multi_select('YEAR')
chart3 = cuxfilter.charts.bar('DAY_WEEK', x_label_map=label_map)
chart4 = cuxfilter.charts.bar('MONTH')

#declare dashboard
d = cux_df.dashboard([chart1, chart2, chart3, chart4], layout=cuxfilter.layouts.feature_and_double_base, title='Auto Accident Dataset')
#run the dashboard as a webapp:
await d.preview()

it got gaierror: [Errno -2] Name or service not known

how to fix it？

**Comment by AjayThorve** [comment]
@liukai1919, thanks for the question. This is a known issue, and the same has been fixed in a hotfix release cuxfilter 0.16.1. You can install it using - 

`conda install -c rapidsai -c nvidia -c conda-forge  -c defaults cuxfilter=0.16.1`

**Comment by liukai1919** [comment]
> @liukai1919, thanks for the question. This is a known issue, and the same has been fixed in a hotfix release cuxfilter 0.16.1. You can install it using -
> 
> `conda install -c rapidsai -c nvidia -c conda-forge -c defaults cuxfilter=0.16.1`
> 
> let me know if issues still persist

thank you, its works good
