### ISSUE TITLE
[FEA] Add support to series numerical index to 'x' and 'y' parameters 

### ISSUE THREAD

**Issue by miguelusque** [rapidsai/cuxfilter#243]
**Is your feature request related to a problem? Please describe.**
Hi!

I have noticed that some charts, like `cuxfilter.charts.datashader.line` requires `x` and `y` parameters to be a series name (str format). 

I think it would be handy if those parameters would also support int values. Some dataframes do not have string column names, and just numeric values (0, 1, 2 ...).

Hope it helps!
Miguel

**Comment by AjayThorve** [comment]
datashader uses xarray to render rastered images, and xarray does not support numerical dimensions yet, this would require hacks within cuxfilter to work (handle conversions to string and ints), which ended up being much more complicated than just having a requirement of string based column names from the end-user api
