### ISSUE TITLE
[QST] Hue feature in cuxfilter

### ISSUE THREAD

**Issue by sijopkd** [rapidsai/cuxfilter#250]
How can we show different colors based on a categorical variable? I have attached a pandas example. 

Thank you 
![Screen Shot 2021-02-23 at 3 12 18 PM](https://user-images.githubusercontent.com/24625433/108909417-25171980-75ea-11eb-9dcc-2674ba0123b3.png)

**Comment by AjayThorve** [comment]
Hey @sijopkd , thanks for the question. I don't think multi-bar charts are implemented yet. If you are looking for a quicj way to plot static charts with cudf, especially the one requested, I would suggest having a look at hvplot's cudf implementation - https://hvplot.holoviz.org/reference/pandas/bar.html#pandas-gallery-bar, (just replace pandas with cudf dataframes) and `hvplot.cudf` api should help you plot it rather easily.

cuxfilter focusses on a few specific charts, which allows it to have default callbacks using datatiles for quick interaction. We haven't yet implemented the multi-bar chart, but if the request is just for a static chart, hvplot should be enough.

**Comment by sijopkd** [comment]
Thanks @AjayThorve for your prompt response. 

hvplot works great, however I did not notice any performance improvements using hvplot instead of using pandas plots. Converting cudf dataframes to pandas and plotting them was quicker than using hvplot. 

I highly appreciate your quick reponse. 

Thanks again,
Sijo

**Comment by AjayThorve** [comment]
@sijopkd you will start noticing a performance difference after about a million datapoints in the dataframe. Below that, pandas performance is going to be comparable
