### ISSUE TITLE
[FEA] API change for Panel Widget

### ISSUE THREAD

**Issue by exactlyallan** [rapidsai/cuxfilter#256]
**Issue:**
Currently panel widgets are considered 'charts' e.g. `charts.range_slider`, but are not considered part of the layout chart order. This can be confusing in creating custom layouts. 

**Proposal:**
Move 'Panel Widgets' outside of charts, up one level e.g.:
`cuxfilter.charts.multi_select('year')` -> `cuxfilter.panel_widget.multi_select('year')`

**Comment by AjayThorve** [comment]
@exactlyallan one solution to this problem is we add a `sidebar` argument to this `dashboard` function:

```python
d = cux_df.dashboard(charts=charts_list, sidebar=[widget_chart1, widget_chart2], layout_array=[
    [1, 1, 2, 2],
    [1, 1, 3, 4]
], theme=cuxfilter.themes.rapids, title="Layout - Custom")
```
that way, only  list of `charts` are considered while computing the layout array

**Comment by exactlyallan** [comment]
For consistency and added functionality, lets make the panel widgets able to be used in the chart layout area as well.
