### ISSUE TITLE
[BUG] Auto Accidents Example Mapping Issue

### ISSUE THREAD

**Issue by exactlyallan** [rapidsai/cuxfilter#260]
For the [auto accidents example notebook](https://docs.rapids.ai/api/cuxfilter/stable/examples/auto_accidents_example.html) when scrubbing years between 2012-2014 the map layout forms a grid or the data points become too large.  The number of data points seems correct - possibly bad data?

This is using 0.19 fresh install.

**Comment by AjayThorve** [comment]
@exactlyallan you guessed it right, corrupt data

**Comment by exactlyallan** [comment]
@AjayThorve bump!

**Comment by AjayThorve** [comment]
@exactlyallan Not sure how we can resolve this, the data provided was corrupt itself. One thing we can do is get rid of years 2012-2014

**Comment by exactlyallan** [comment]
@AjayThorve make note of the bad data in the example docs and readme etc.
