### ISSUE TITLE
[FEA] Provide more tiles options for cuxfilter.charts.choropleth

### ISSUE THREAD

**Issue by kshitizgupta21** [rapidsai/cuxfilter#266]
**Describe the solution you'd like**
@AjayThorve As discussed, it would be great if charts.choropleth can support another tile option besides mapbox like CARTODBPOSITRON and Stamen.

**Comment by AjayThorve** [comment]
@kshitizgupta21 you can use the `map_style` parameter of the choropleth chart and directly pass one of these urls -> https://deck.gl/docs/api-reference/carto/basemap#supported-basemaps, as the value for map_style. 

That should generate a basemap without needing a token.

I'll still go ahead and push the changes to use these basemaps if no token is provided, but this should resolve your issue
