### ISSUE TITLE
[QST] no charts appearing?

### ISSUE THREAD

**Issue by Data-drone** [rapidsai/cuxfilter#274]
I am trying to draw just a simple bar chart with cuxfilter in jupytrerlab 3.0

I have followed the example code here. https://docs.rapids.ai/api/cuxfilter/stable/charts/bokeh_charts.html

I ended up getting an error about `pn.extension` so I installed jupyterlab_pyviz and then ran

```
import panel as pn
pn.extension()
```

that got rid of that error.

then I ran the code:

```
# test with cuxfilter
import cuxfilter

cux_df = cuxfilter.DataFrame.from_dataframe(history_count)
bar_chart_1 = cuxfilter.charts.bar('MONTHS_BALANCE')
bar_chart_1.view()
```

`MONTHS_BALANCE` is  a cudf column of type int32
history_count is a `cudf.core.dataframe.DataFrame`

After the `bar_chart_1.view()` call I see the header of the chart but no actual chart?

![Screenshot from 2021-04-27 23-29-28](https://user-images.githubusercontent.com/4410493/116249723-6fff0a00-a7b0-11eb-9ed2-4f31eaf863fb.png)

There is no chart? nor any error messages to indicate what went wrong?

**Comment by AjayThorve** [comment]
Hi @Data-drone, the way cuxfilter works is,
1. create a cuxfilter Dataframe
2. declare charts
3. connect the charts to cuxfilter Dataframe

while you did do steps 1 and 2, you missed the step where we connect the chart to cuxfilter Dataframe. So the following should work:

```python
import cuxfilter

cux_df = cuxfilter.DataFrame.from_dataframe(history_count)
bar_chart_1 = cuxfilter.charts.bar('MONTHS_BALANCE')

# initialize a cuxfilter dashboard, while linking cux_df and bar_chart_1
dashboard = cux_df.dashboard(charts=[bar_chart_1])

bar_chart_1.view()
```

**Comment by Data-drone** [comment]
Ah thanks
