### ISSUE TITLE
[FEA] [NEW_CHART] Bokeh heatmap

### ISSUE THREAD

**Issue by AjayThorve** [rapidsai/cuxfilter#33]
**Is your feature request related to a problem? Please describe.**
Add support for bokeh heatmap chart type to be used in a crossfilter enabled dashboard

**Describe the solution you'd like**
https://bokeh.pydata.org/en/latest/docs/gallery/les_mis.html as one of the types that can be added to the dashboard with crossfilter functionalities enabled

**Describe alternatives you've considered**
There is an option to use the cudatashader heatmaps but that is not hoverable, and as interactive(info on hover, individual data-point selection to filter) as a bokeh heatmap is.

**Comment by exactlyallan** [comment]
This would be different than the datashader version?

**Comment by AjayThorve** [comment]
Yes, as the datashader version is not interactive. Could be useful especially for lower number of datapoints

**Comment by exactlyallan** [comment]
Justs defaults to datashader.
