### ISSUE TITLE
How to implement Bokeh heatmaps using NVIDIA RAPIDS library for interactive dashboard visualisation?

### ISSUE THREAD

**Issue by Sri-Harish-Kalidass** [rapidsai/cuxfilter#342]
Hi all,

I am currently experimenting with heatmap based interactive visualisation using RAPIDS library and I was able to successfully generate(figure-1) an interactive dashboard using Cuxfilter plugin(which uses Bokeh server and library) however I am only able to select one column in x and y axis and this is very limiting as I need to generate plot (see figure -2)for tens of columns in both x and y axis. Can anyone help with this?

Figure -1 - I am able to generate this type of heatmap

![image](https://user-images.githubusercontent.com/43203550/150140924-888d6f18-1979-44ca-a803-29d5cb71a523.png)

Figure -2 - I would like to generate this type of heatmap
![image](https://user-images.githubusercontent.com/43203550/150141147-b05aa5a5-672e-4810-865b-4cb7ceb6c8bc.png)

Many thanks

**Comment by AjayThorve** [comment]
linking the related stackoverflow question (https://stackoverflow.com/questions/70770107/how-to-implement-bokeh-heatmaps-using-nvidia-rapids-library-for-interactive-dash). 
As mentioned by bryan, please provide more details and share some actual code to focus the discussion, specifically a [Minimal Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by AjayThorve** [comment]
answered on the stackoverflow page
