### ISSUE TITLE
[QST] Can one filter the dashboard scatter plot through querying the cuxfilter.DataFrame through arbitrary filters

### ISSUE THREAD

**Issue by whaowhao** [rapidsai/cuxfilter#344]
Can one add programmatical filters such as 
`df[df["text"].apply(lambda x: "justin" in x)]`
and let let show in the dashboard interactive?

I am trying to use cuxfilter to interactively explore text data, so have such arbitrary filters can be extremely helpful.

**Comment by AjayThorve** [comment]
you mean execute `df[df["text"].apply(lambda x: "justin" in x)]` in a different notebook cell to update the underlying dataframe, and let the dashboard reflect that?

Some example code snippet on what  you are trying to achieve might be helpful,

**Comment by whaowhao** [comment]
yes exactly. 

```
df_cu = cudf.read_parquet('log.parquet')
cux_df = cuxfilter.DataFrame.from_dataframe(df_cu)
chart0 = cuxfilter.charts.scatter(x='x', y='y')
d = cux_df.dashboard([chart0])
d.show()
df_cu.text.isin(['justin bieber']) # want to use this to update the dashboard
```

**Comment by AjayThorve** [comment]
you can do the following
```python
df_cu = cudf.read_parquet('log.parquet')
cux_df = cuxfilter.DataFrame.from_dataframe(df_cu)
chart0 = cuxfilter.charts.scatter(x='x', y='y')
d = cux_df.dashboard([chart0])
d.show() # or d.app() introduced in the last PR, which runs the dashboard completely interactive within the notebook

d._reload_charts(df_cu.text.isin(['justin bieber']))
```

**Comment by whaowhao** [comment]
Thanks, does this preserve filters already created in the dashboard or does it clear everything?

**Comment by AjayThorve** [comment]
nope, it will just do hard reload based on the data you provide. 

You can however, use export the current state of filters, using `d.export()` which will return the visually queried dataset, and run something like

```python
d._reload_charts(d.export().text.isin(['justin bieber']))
```

although, a back-and-forth of command line and visual querying wouldn't be stable as it's not designed to work this way. I'll make a note of it to add a more stable, non-hacky way of updating the dataframe underneath.

**Comment by AjayThorve** [comment]
@whaowhao feel free to reopen the issue persists, but looks like the current solution works for you. As I said, I'll work on a more stable way to do this in a future release.

**Comment by whaowhao** [comment]
the hack unfortunately didn't work, executing the following command results in error below.

`d._reload_charts(d.export()[d.export().text.isin(['justin bieber'])])` 

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_21552/2247995894.py in <module>
----> 1 d._reload_charts(d.export()[d.export().text.isin(['justin bieber'])])

~/anaconda3/envs/rapids-21.12/lib/python3.8/site-packages/cuxfilter/dashboard.py in _reload_charts(self, data, include_cols, ignore_cols)
    719         for chart in self.charts.values():
    720             if chart.name not in ignore_cols and chart.name in include_cols:
--> 721                 chart.reload_chart(data, patch_update=True)
    722 
    723     def _calc_data_tiles(self, cumsum=True):

~/anaconda3/envs/rapids-21.12/lib/python3.8/site-packages/cuxfilter/charts/datashader/plots.py in reload_chart(self, data, patch_update)
    335             if len(data) == 0:
    336                 data = cudf.DataFrame({k: cp.nan for k in data.columns})
--> 337             self.interactive_image.update_chart(data_source=data)
    338 
    339     def add_selection_geometry_event(self, callback):

~/anaconda3/envs/rapids-21.12/lib/python3.8/site-packages/cuxfilter/charts/datashader/custom_extensions/interactive_image.py in update_chart(self, **kwargs)
    131         }
    132         self.kwargs.update(kwargs)
--> 133         self.update_image(dict_temp)
    134 
    135     _callbacks = {}

~/anaconda3/envs/rapids-21.12/lib/python3.8/site-packages/cuxfilter/charts/datashader/custom_extensions/interactive_image.py in update_image(self, ranges)
    197         )
    198 
--> 199         self.ds.data.update(new_data)
    200 
    201     def _repr_html_(self):

~/anaconda3/envs/rapids-21.12/lib/python3.8/site-packages/bokeh/core/property/wrappers.py in update(self, *args, **kwargs)
    395         for (owner, descriptor) in self._owners:
    396             hint = ColumnDataChangedEvent(owner.document, owner, cols=list(cols))
--> 397             descriptor._notify_mutated(owner, old, hint=hint)
    398 
    399         return result

~/anaconda3/envs/rapids-21.12/lib/python3.8/site-packages/bokeh/core/property/descriptors.py in _notify_mutated(self, obj, old, hint)
    594         value = self.property.prepare_value(obj, self.name, value, hint=hint)
    595 
--> 596         self._set(obj, old, value, hint=hint)
    597 
    598     def _trigger(self, obj: HasProps, old: Unknown, value: Unknown, *,

~/anaconda3/envs/rapids-21.12/lib/python3.8/site-packages/bokeh/core/property/descriptors.py in _set(self, obj, old, value, hint, setter)
    557 
    558         # for notification purposes, "old" should be the logical old
--> 559         self._trigger(obj, old, value, hint=hint, setter=setter)
    560 
    561     # called when a container is mutated "behind our back" and

~/anaconda3/envs/rapids-21.12/lib/python3.8/site-packages/bokeh/core/property/descriptors.py in _trigger(self, obj, old, value, hint, setter)
    635         """
    636         if hasattr(obj, 'trigger'):
--> 637             obj.trigger(self.name, old, value, hint, setter)
    638 
    639 

~/anaconda3/envs/rapids-21.12/lib/python3.8/site-packages/bokeh/model/model.py in trigger(self, attr, old, new, hint, setter)
    565         # chain up to invoke callbacks
    566         descriptor = self.lookup(attr)
--> 567         super().trigger(descriptor.name, old, new, hint=hint, setter=setter)
    568 
    569     def _attach_document(self, doc: Document) -> None:

~/anaconda3/envs/rapids-21.12/lib/python3.8/site-packages/bokeh/util/callback_manager.py in trigger(self, attr, old, new, hint, setter)
    192         if self.document is not None:
    193             from ..model import Model
--> 194             self.document.callbacks.notify_change(cast(Model, self), attr, old, new, hint, setter, invoke)
    195         else:
    196             invoke()

~/anaconda3/envs/rapids-21.12/lib/python3.8/site-packages/bokeh/document/callbacks.py in notify_change(self, model, attr, old, new, hint, setter, callback_invoker)
    234 
    235         event = ModelChangedEvent(doc, model, attr, old, new, serializable_new, hint, setter, callback_invoker)
--> 236         self.trigger_on_change(event)
    237 
    238     def notify_event(self, model: Model, event: ModelEvent, callback_invoker: Invoker) -> None:

~/anaconda3/envs/rapids-21.12/lib/python3.8/site-packages/bokeh/document/callbacks.py in trigger_on_change(self, event)
    376             for cb in self._change_callbacks.values():
    377                 cb(event)
--> 378         invoke_with_curdoc(doc, invoke_callbacks)
    379 
    380     def unhold(self) -> None:

~/anaconda3/envs/rapids-21.12/lib/python3.8/site-packages/bokeh/document/callbacks.py in invoke_with_curdoc(doc, f)
    406 
    407     with patch_curdoc(curdoc):
--> 408         return f()
    409 
    410 

~/anaconda3/envs/rapids-21.12/lib/python3.8/site-packages/bokeh/document/callbacks.py in invoke_callbacks()
    375         def invoke_callbacks() -> None:
    376             for cb in self._change_callbacks.values():
--> 377                 cb(event)
    378         invoke_with_curdoc(doc, invoke_callbacks)
    379 

~/anaconda3/envs/rapids-21.12/lib/python3.8/site-packages/bokeh/document/callbacks.py in <lambda>(event)
    261     def on_change_dispatch_to(self, receiver: Any) -> None:
    262         if not receiver in self._change_callbacks:
--> 263             self._change_callbacks[receiver] = lambda event: event.dispatch(receiver)
    264 
    265     def on_event(self, event: str | Type[Event], *callbacks: EventCallback) -> None:

~/anaconda3/envs/rapids-21.12/lib/python3.8/site-packages/bokeh/document/events.py in dispatch(self, receiver)
    398 
    399         '''
--> 400         super().dispatch(receiver)
    401         if hasattr(receiver, '_document_model_changed'):
    402             cast(DocumentModelChangedMixin, receiver)._document_model_changed(self)

~/anaconda3/envs/rapids-21.12/lib/python3.8/site-packages/bokeh/document/events.py in dispatch(self, receiver)
    221         super().dispatch(receiver)
    222         if hasattr(receiver, '_document_patched'):
--> 223             cast(DocumentPatchedMixin, receiver)._document_patched(self)
    224 
    225     def generate(self, references: Set[Model], buffers: Buffers) -> DocumentPatched:

~/anaconda3/envs/rapids-21.12/lib/python3.8/site-packages/bokeh/server/session.py in _document_patched(self, event)
    243 
    244         if self._pending_writes is None:
--> 245             raise RuntimeError("_pending_writes should be non-None when we have a document lock, and we should have the lock when the document changes")
    246 
    247         # TODO (havocp): our "change sync" protocol is flawed because if both

RuntimeError: _pending_writes should be non-None when we have a document lock, and we should have the lock when the document changes

**Comment by AjayThorve** [comment]
Can you update to the latest nightly version 22.02 and try again?

**Comment by AjayThorve** [comment]
@whaowhao did it work?

**Comment by whaowhao** [comment]
I tried it but the same error happened, in the end I resorted to multiselect.

**Comment by AjayThorve** [comment]
Seems like a different solution was used to resolve the issue.
