### ISSUE TITLE
Scatterplot change colour transparency for selected/unselected points

### ISSUE THREAD

**Issue by whaowhao** [rapidsai/cuxfilter#367]
While exploring data in a scatterplot, it'd be useful to mark already explored points to a different colour to avoid duplicated exploration. Is there a way to do that? 

Furthermore, it'd be useful to make unselected points transparent with a low alpha instead of erasing them entirely while selecting a cluster of points (current default behaviour). Is that possible with cuxfilter?

**Comment by AjayThorve** [comment]
@whaowhao that seems like a reasonable feature request, and should certainly be possible. Have added it to the to-do list!! Thanks!

**Comment by exactlyallan** [comment]
@whaowhao great suggestions!
