### ISSUE TITLE
[FEA] Increase pydeck support to =0.6.2

### ISSUE THREAD

**Issue by gregory1506** [rapidsai/cuxfilter#397]
Many pydeck features like tripslayer and pathlayer would be quite useful in cuspatial.

**Comment by AjayThorve** [comment]
thanks @gregory1506, definitely sounds useful. We will get to this next as soon as we have resources available.

**Comment by ekungurov** [comment]
pydeck 0.5 uses MapBox. MapBox went commercial and now requires API key to function. Without subscription map tiles are not shown at all. Pydeck v0.6 onwards provides basemap tiles through Carto and works for free.

**Comment by AjayThorve** [comment]
Thanks @ekungurov, we are in process of updating the pydeck version
