### ISSUE TITLE
[suggestion] Support graph visualization

### ISSUE THREAD

**Issue by archenroot** [rapidsai/cuxfilter#4]
Its just idea to work with and/or suggestion...

The graph visualization is emerging as well quite quickly although the storage layer is still the bottleneck (not much scallable graph database exists and those which does sharding accross nodes are not well proven yet - one for all is dgraph), but still visualization of graph data is something Rapids shouldn't leave behind (as soon as you work with Gunrock and support cuGraph API).

So here is one cool candidate on graph visualizations based on WebGL tech:
https://github.com/vasturiano/3d-force-graph

Maybe something to integrate with cuGraph via cuxfilter architecture.

**Comment by exactlyallan** [comment]
Yep the RAPIDS group is working on this in several areas - though probably wont be released through cuxfilter.
