### ISSUE TITLE
[FEA] 3rd party dependency GPU tests

### ISSUE THREAD

**Issue by AjayThorve** [rapidsai/cuxfilter#452]
Work on a way to automate GPU testing for 3rd party dependencies with GPU support, mainly, datashader, holoviews and hvplot. Current plan of action involves:

- [x] GHA workflow to install and test the GPU functionality of these libraries (#456)
 - [ ] ~~lambda function to create an endpoint, which will trigger this workflow~~
 - [ ] ~~expose it to anaconda devs, to trigger this workflow on or before project releases~~
 - [ ] ~~subscribe to workflows via slack/teams~~

cc @exactlyallan

**Comment by exactlyallan** [comment]
@raydouglass + @ajschmidt8  Could you review this approach to see if using lambda functions violates any security policies? I.E. external party triggering a PR.

**Comment by ajschmidt8** [comment]
> @raydouglass + @ajschmidt8 Could you review this approach to see if using lambda functions violates any security policies? I.E. external party triggering a PR.

We might want to brainstorm on a better way for this. In hindsight, I'm not a fan of the Lambda solution that I suggested.

It involves deploying some additional AWS infrastructure that we'd have to manage.

Is a weekly or every-other-nightly cron job suitable?

If I recall correctly, I think you guys mentioned that we don't necessarily need to run it every night.

As long as the jobs don't take an unusually long amount of time to run, I don't see any harm in just running it on a scheduled basis.

**Comment by exactlyallan** [comment]
@ajschmidt8 Scheduled jobs could be an option - but would this still be a thing that can test a PR?

**Comment by AjayThorve** [comment]
> > @ajschmidt8 Scheduled jobs could be an option - but would this still be a thing that can test a PR?
> 
> Do you mean test a PR from one of the third-party repositories?

yep

**Comment by ajschmidt8** [comment]
> > Do you mean test a PR from one of the third-party repositories?
> 
> yep

Yes, we could support that.

We can configure the job in such a way that it will run on a recurring basis against the default branch _or_ it can be manually triggered and passed a particular PR that it should test.

If I remember correctly, @AjayThorve has already set up the new workflow to work like that.

**Comment by exactlyallan** [comment]
Okay, as long as there is at least an option. Its a bit annoying to manually trigger it, but what are you going to do... the results of the run are visible through Slack bot but is there any other option?

**Comment by exactlyallan** [comment]
**New Proposal:**

- [x] A. GHA done with #456 
- [ ] B. Set recurring runs to catch dependencies issues
- [ ] C. Enable RAPIDS org to manually run for a specific external PR to help external devs

For C. the process would be: 

- External dev (i.e. for datashader) creates an issue (for now on cuxfilter) requesting to run test for their PR
- Someone in RAPIDS org (PIC @AjayThorve) kicks off GHA
- Result of run gets posted back to issue / is publicly visible

**Comment by exactlyallan** [comment]
@ajschmidt8 @AjayThorve Anaconda folks like this implementation, lets kick off the weekly runs. Sunday evening work?

**Comment by ajschmidt8** [comment]
yup, that works for me

**Comment by AjayThorve** [comment]
@ajschmidt8, is the weekly workflow trigger active?

**Comment by ajschmidt8** [comment]
> @ajschmidt8, is the weekly workflow trigger active?

It doesn't look like it: https://github.com/rapidsai/cuxfilter/blob/1fde9c992df74a79696500e532e11d0c1248262e/.github/workflows/test-external.yaml#L3-L19

You'll need to add a `schedule` event to that workflow to trigger it on a weekly basis. See the docs below for more details

- https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule

**Comment by AjayThorve** [comment]
3rd party dependency testing works now via this GHA -> https://github.com/rapidsai/cuxfilter/actions/workflows/test-external.yaml
