### ISSUE TITLE
[BUG] Cuxfilter dashboard does not start if hvPlot used previously in Notebook

### ISSUE THREAD

**Issue by exactlyallan** [rapidsai/cuxfilter#484]
**Describe the bug**
When creating notebooks that uses both hvplot and cuxfilter (in that order), the cuxfilter dashboard button does not load and subsequent hvplots do not load as well. Browser console logs show bokeh.js fails to load. Reloading bokeh.js via extensions resolves the issue, but is not a fix. 

**Steps/Code to reproduce bug**
Follow Notebook Gist: https://gist.github.com/exactlyallan/400218bfa084b49c3e0f4e4fb122630f

**Expected behavior**
Charts do not appear. 

**Environment details (please complete the following information):**
 - Environment location: local Ubuntu 22.04, RAPIDS 23.04, JuplyterLab 3.6.4
 - Method of cuxfilter install: Conda

**Comment by AjayThorve** [comment]
This seems to be working (the gist provided) now after the recent updates. (hvplot 0.8.4, holoviews 1.17.0, cuxfilter 23.08, bokeh 3.2.1)

Closing this now, feel free to open it if the issue persists.
