### ISSUE TITLE
[BUG] Datashader Docs Line Charts not rendering

### ISSUE THREAD

**Issue by exactlyallan** [rapidsai/cuxfilter#486]
**Describe the bug**
Datashader line charts not rendering in docs 23.04 and 23.06

**Steps/Code to reproduce bug**
See: https://docs.rapids.ai/api/cuxfilter/stable/charts/datashader_charts/#line-chart
and https://docs.rapids.ai/api/cuxfilter/stable/charts/datashader_charts/#stacked-lines-chart

**Expected behavior**

**Comment by AjayThorve** [comment]
this is now fixed
