### ISSUE TITLE
Docker build keeps failing

### ISSUE THREAD

**Issue by dkim777** [rapidsai/cuxfilter#5]
When issuing docker build command(step 2 in installation), I get following error.
any ideas?

---------------------
Solving environment: ...working... failed

PackagesNotFoundError: The following packages are not available from current channels:

  - cudf=0.4.0

Current channels:

  - https://conda.anaconda.org/numba/linux-64
  - https://conda.anaconda.org/numba/noarch
  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/rapidsai/linux-64
  - https://conda.anaconda.org/rapidsai/noarch
  - https://conda.anaconda.org/nvidia/linux-64
  - https://conda.anaconda.org/nvidia/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by exactlyallan** [comment]
The rapidsai conda package has recently been updated and no longer includes cudf=0.4.0 in that location. In the cuXfilter repo, you could try updating the [DockerFile](https://github.com/rapidsai/cuxfilter/blob/master/Dockerfile) to use cudf=0.5, BUT we've not tested that yet ( I've been on leave! ).
Alternatively you could use the older conda package with version 0.4.0 here
[conda cudf](https://anaconda.org/rapidsai/cudf/files ).

**Comment by dkim777** [comment]
using cudf=0.5 causes different error below,
I've tried other versions by only chaining version numbers, but all with same result.
How should I update the code to specifically point to older conda package like you have suggested?
I really hope I can try this GTC mortgage demo on AWS P3 machines I'm going to use.
Thanks!
-----------------------------------------
Solving environment: ...working... failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - cudf=0.5 -> pandas[version='>=0.23.4']
  - pandas=0.20.3
Use "conda search <package> --info" to see the dependencies for each package.

**Comment by dkim777** [comment]
Docker build completed successfully after modifying following three items.
Panda_version=0.23.4
Pyarrow_version=0.12.0
cudf=0.5

but GTC demo doesn't show the result.
I can see the control graphics but no map or data on graphs.
I have verified that 146M_predictions_v2.arrow file is in /usr/src/app/node_server/uploads in the running container viz.
Any help would be appreciated.
Thanks.

**Comment by dkim777** [comment]
![image](https://user-images.githubusercontent.com/12587920/53058509-484de200-3481-11e9-9930-1a551c4d6b81.png)

**Comment by exactlyallan** [comment]
Ok, progress - could you open the browser web developer javascript console and let us know the log messages?

**Comment by AjayThorve** [comment]
You might want to check the GPU usage. We have tested this dataset with the titan rtx gpu with 24GB of GPU memory. This dataset uses around 12-15GB. 

For the maps to be visible, make sure you have added the mapbox token in the config.json file while building the container. You can get one for free here -> https://docs.mapbox.com/help/glossary/access-token. Irrespective of the maps being visible though, the data should be loaded and visible if everything else works as expected.

And as @exactlyallan said, the console logs might be helpful

**Comment by dkim777** [comment]
Got it working finally,  Thanks!!
The server IP should be the external facing IP from where your client is using from, not localhost or VIP.
This is an awesome demo of GPU machine,  any other demo but with multiple GPU usage?
![image](https://user-images.githubusercontent.com/12587920/53136808-5fa6d100-354e-11e9-8d72-24b6ccaaafcd.png)

**Comment by exactlyallan** [comment]
@dkim777 Glad you got it working - see my [issue reply](https://github.com/rapidsai/cuxfilter/issues/3#issuecomment-450432159) for some details, but in short once [dask-cudf](https://github.com/rapidsai/dask-cudf) is built out more we _might_ create a multi-gpu cuXfilter.
