### ISSUE TITLE
[QST] Where is the GTC demo?

### ISSUE THREAD

**Issue by archenroot** [rapidsai/cuxfilter#50]
**What is your question?**
I am just trying to pack some demo for our team and the original GTC demo is gone, its completely removed or just moved elsewhere? ...ok I can search in commit history to find ./demos folder removal as well, but maybe someone can enlighten me? 💃

**Comment by AjayThorve** [comment]
Heh @archenroot, It's still there. We moved it to the /JavaScript folder.  Focus is on active development of the python package which tries to create same level of dashboards using a few lines of python code, within a jupyter notebook or as a separate web app.
