### ISSUE TITLE
[QST] Streaming Integration and Catalog Based Dashboarding

### ISSUE THREAD

**Issue by archenroot** [rapidsai/cuxfilter#51]
I experimented with cuDF, but at moment working on new streaming platform and would like to introduce GPU accelerated real time analytics as front db, I will hint a streaming platform design in general just as sequence of steps:
data source -> topic(with s3 auto sink) -> data standartization (spark with griffin) -> topic (with s3 auto sink) -> schema standartization (spark) -> clean data topic (with s3 sink), these are highly atomic data more normalized.

Now this clean data topis(s) i would like to use Spark to materialize in set of different cuDFs for application analytics (turn into more denormalized sets for fast access). Spark will be reasonsble to stream data in and keep cuDFs enough large so they can fit into GPU ram.

These cuDFs will be registerd (or that is idea in our data catalog solution), so eventually user will be able to pick them from dashboard and start using them.

Q1: Can be cuDF shared accross processes? So Spark/Dask will update data in cuDF and cuxfilter will access it to query only(read access)?
Q2: Do you plan to reach with cuxfilter something like OmniSci is having with their Immerse Visual Analytics system? So you can have multiple data sets (cuDFs) and you can use them in dashboards and dynamically by drag and drop style work with them?
https://www.omnisci.com/demos/ships/

I know this topic requires wider discussion, just more asking if reaching such point is your vision or not.

Anyway thank you for your hard and cool interesting work on this.

Ladislav

**Comment by exactlyallan** [comment]
Thanks @archenroot you have big plans!

If I understand your first question correctly: once a dataframe is loaded into GPU memory, it is accessible from anywhere. For example, if you load a cuDF dataframe from one notebook you can access it via a separate notebook. We don't have any direct visualization integration with Spark/Dask per say, but cuDF does have [dask_cuDF as part of its offering](https://docs.rapids.ai/api/cudf/stable/) and RAPIDS is actively developing [closer Spark integration](https://medium.com/rapids-ai/nvidia-gpus-and-apache-spark-one-step-closer-2d99e37ac8fd). There is also a [cuDF cuStreamz](https://github.com/rapidsai/cudf/tree/branch-0.11/python/custreamz) library that might also be helpful.

For your second question: We don't plan on making an OmniSci level application with drag and drop type interface as our focus right now is more based on notebooks for the "interface" to creating dashboards. However, the updated cuXfilter does make it ALMOST drag and drop. 

Feel free to keep asking questions, we are open to hearing feature ideas.
