### ISSUE TITLE
Check compatability with cuDF pandas 2.0 migration

### ISSUE THREAD

**Issue by exactlyallan** [rapidsai/cuxfilter#512]
Per https://github.com/rapidsai/cudf/pull/13535 check cuxfilter for issues with Pandas 2.0.

**Comment by jakirkham** [comment]
Recently cuDF added Pandas 2.x support with PR ( https://github.com/rapidsai/cudf/pull/14916 ). This introduced some breaking changes. Given this, it might be worth checking how cuxfilter is working with cuDF following that upgrade

**Comment by bdice** [comment]
CI is passing in https://github.com/rapidsai/cuxfilter/pull/568, so it's possible that no changes are needed.

**Comment by galipremsagar** [comment]
> CI is passing in #568, so it's possible that no changes are needed.

It's targeted to `24.02`, which is still pandas-1.5.x. So we still need someone to investigate it on `24.04`

**Comment by bdice** [comment]
🤦‍♂️ Good eye, @galipremsagar! However, CI also passed yesterday on the CUDA 12.2 PR https://github.com/rapidsai/cuxfilter/pull/563 which targets 24.04. That PR included [cudf 24.04.00a356 (build cuda12_py310_240206_g20ed009003_356)](https://github.com/rapidsai/cuxfilter/actions/runs/7803061909/job/21282210912?pr=563#step:7:786) and [pandas 2.1.4](https://github.com/rapidsai/cuxfilter/actions/runs/7803061909/job/21282210912?pr=563#step:7:809). This was re-run yesterday.

**Comment by jakirkham** [comment]
Based on offline discussion with Ajay, sounds like there is work still needed. He is looking into it

**Comment by jakirkham** [comment]
WIP fix submitted as PR: https://github.com/rapidsai/cuxfilter/pull/569
