### ISSUE TITLE
[BUG] Update usage of cudf.core.column.arange to cudf.core.column.as_column

### ISSUE THREAD

**Issue by vyasr** [rapidsai/cuxfilter#565]
**Describe the bug**
Tests are currently failing in CI, see e.g. https://github.com/rapidsai/cuxfilter/pull/564. The failures are because cuxfilter uses an internal method of cudf that was removed in https://github.com/rapidsai/cudf/pull/14689. The errors can be fixed by replacing those usages in the same fashion as was done internally in that cudf PR.

**Comment by AjayThorve** [comment]
@vyasr actually this is an issue with cuspatial's usage of `arange`, which is a direct dependency for cuxfilter. I'll create a PR for cuspatial to fix it

**Comment by AjayThorve** [comment]
Added a PR to fix this issue in cuspatial : https://github.com/rapidsai/cuspatial/pull/1323

**Comment by AjayThorve** [comment]
tests pass now: https://github.com/rapidsai/cuxfilter/actions/runs/7538330530

closing
