### ISSUE TITLE
[BUG] Not able to plot using cuxfilter after activating cudf.pandas kernel

### ISSUE THREAD

**Issue by patelmiteshn** [rapidsai/cuxfilter#605]
**Describe the bug**
using cuxfilter for plotting issues the following error: `ValueError: ClassSelector parameter 'InteractiveDatashader.source_df' value must be an instance of (DataFrame, DataFrame)`. 

The notebook is modified from [this version](https://github.com/rapidsai-community/notebooks-contrib/blob/main/getting_started_materials/intro_tutorials_and_guides/13_Introduction_to_Time_Series_Data_Analysis_using_cuDF.ipynb). 

The modifications were made to incorporate zero code change with `cudf.pandas` kernel

**Steps/Code to reproduce bug**
To reproduce the bug follow this [notebook](https://github.com/patelmiteshn/datascience/blob/main/dev/Time_Series_Data_Analysis_using_cuDF.ipynb)

**Expected behavior**
The script should be plotting a line graph

**Environment details (please complete the following information):**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
    Ubuntu 22.02  on local desktop with RTX A6000
 - Method of cuxfilter install: [conda, Docker, or from source]
   pip install (https://docs.rapids.ai/install)
 

**Additional context**

**Comment by exactlyallan** [comment]
We are waiting on an upstream fix that enables datashader to work cudf.pandas - https://github.com/rapidsai/cudf/issues/15694

**Comment by Matt711** [comment]
The proxy DataFrame returned from `InteractiveDatashader.source_df` when `cudf.pandas` is turned on is not an instance of `cudf.DataFrame` but is of `pd.DataFrame`.
