### ISSUE TITLE
[FEA] Add support for javascript/flask/RPC

### ISSUE THREAD

**Issue by davidpham87** [rapidsai/cuxfilter#61]
**Is your feature request related to a problem? Please describe.**
The whole web community would profit from a decoupling of some features features of cuxfilter. Instead of adapating major visualization pacakges to cuxfilter, we could expose the features as API and let the JS community create novel solution.

**Describe the solution you'd like**
Expose some API for React/JS users to leverage on cuxfilter. The first use case would be for electron/local apps as the size of the data set could impose some problems.

**Describe alternatives you've considered**
Use *cudf* directly and expose them through a flask API.

**Additional context**
Although Jupyter notebook is the main target of cuxfilter, I think the package would have incredible success if the whole JS community could leverage on it.

**Comment by exactlyallan** [comment]
@davidpham87 thanks for the input - we agree, but are still planning on the best way to proceed.

**Comment by exactlyallan** [comment]
Working on a non-python alternative.
