### ISSUE TITLE
[BUG] cudf Series code failing: "TypeError: use cudf.Series._from_data"

### ISSUE THREAD

**Issue by jameslamb** [rapidsai/cuxfilter#618]
**Describe the bug**

On 24.10, several tests are failing like this:

> TypeError: Use cudf.Series._from_data for constructing a Series from ColumnAccessor or a ColumnBase

Observed this in CI that wasn't touching any Python code (e.g. #616).

**Steps/Code to reproduce bug**

CI from #616: ([build link](https://github.com/rapidsai/cuxfilter/actions/runs/10287120625/job/28469766465?pr=616))

**Expected behavior**

N/A

**Environment details (please complete the following information):**

Using the latest `cudf` 24.10 nightlies.

This does not appear to be limited to a specific subset of Python version, CPU architecture, or CUDA version.
It affects both wheels and conda packages.

**Additional context**

I believe this is the same root cause as https://github.com/rapidsai/cuspatial/issues/1433. And there are similar reports in other RAPIDS projects:

* https://github.com/rapidsai/cuspatial/pull/1434
* https://github.com/rapidsai/cuml/issues/6017

`cuxfilter` needs to adapt to these changes: https://github.com/rapidsai/cudf/pull/16454

For reference, here's how @mroeschke is approaching this in `cuspatial`: https://github.com/rapidsai/cuspatial/pull/1434

**Comment by mroeschke** [comment]
Looks like tests from this most recent `test` build are generally passing now https://github.com/rapidsai/cuxfilter/actions/runs/10355831367

Is it safe to close this out?

**Comment by jameslamb** [comment]
Yep, I see other test failures there but it does look like this issue has been addressed by the changes from `cuspatial`. I agree we can close this.

Thanks @mroeschke !
