### ISSUE TITLE
[DOC] Adding Gallery to docs

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/cuxfilter#67]
## Report needed documentation

**Report needed documentation**

It would be nice to have a gallery of plots in the docs with each one linking to a simple example. This is great for users who want to do a visual search of the features available in the library when trying to find a good starting point. It's also great for users who want to try something quickly and see how far they get. This is a great way to pull in drive-by users. Some examples of this in other plotting libraries are...

* Bokeh: https://docs.bokeh.org/en/latest/docs/gallery.html
* Matplotlib: https://matplotlib.org/gallery.html
* Seaborn: https://seaborn.pydata.org/examples/index.html

**Describe the documentation you'd like**

Having a gallery of different plot styles with linked example code.

**Steps taken to search for needed documentation**

Skimmed through all of the docs looking for this. Also searched "gallery".

**Comment by AjayThorve** [comment]
This is actually something that is in the planning for the past few weeks, hopefully it's up soon.

**Comment by jakirkham** [comment]
Very glad to hear that! 😄
