### ISSUE TITLE
[QST] Tight pinning of pyproj

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/cuxfilter#71]
**What is your question?**

It looks like `pyproj` both in environments (like [this one]( https://github.com/rapidsai/cuxfilter/blob/315ba8bddd6d4ab5a925d3fd0e03ca5fca36dc7f/conda/environments/cuXfilter_dev_cuda10.1.yml#L12 )) and [the recipe itself]( https://github.com/rapidsai/cuxfilter/blob/315ba8bddd6d4ab5a925d3fd0e03ca5fca36dc7f/conda/recipes/cuxfilter/meta.yaml#L31 ). Am curious what is motivating this tight pinning. Are there changes in later versions of `pyproj` that break this? If so, what are they?

**Comment by AjayThorve** [comment]
It's related to this -> https://github.com/geopandas/geopandas/issues/1213

**Comment by jorisvandenbossche** [comment]
As I also mentioned on the geopandas issue, I would personally not pin to the old pyproj version, if you are to live a while with the deprecation warning (in an interactive environment such as a notebook or console, you should not see it).

Another thing I just noticed, is this line:

https://github.com/rapidsai/cuxfilter/blob/315ba8bddd6d4ab5a925d3fd0e03ca5fca36dc7f/python/cuxfilter/assets/geojson_mapper.py#L15-L16

The `temp_gpd_df.crs["init"]` will break in the next version of geopandas, if we start using `pyproj.CRS` for the `crs` attribute (this will be a breaking change for certain usage patterns, such as this, but there is not really a way to solve this). 
You can already start doing something like this:

```
pyproj.CRS(temp_gpd_df.crs) == "epsg:3857"
```

which should already work now with geopandas 0.6, and also work with a future geopandas 0.7.

**Comment by AjayThorve** [comment]
Resolved, updated pyproj to the latest version, allowing the warnings for now. Also updated the syntax as suggested by @jorisvandenbossche . 

Thanks everyone :)

**Comment by jakirkham** [comment]
Thanks @AjayThorve and @jorisvandenbossche! 😄
