### ISSUE TITLE
[FEA] Alternative to current bokeh server backend for the .show() method

### ISSUE THREAD

**Issue by AjayThorve** [rapidsai/cuxfilter#73]
**Is your feature request related to a problem? Please describe.**
Problem running the client-server architecture for running dashboards, when using cuxfilter within a container

**Describe the solution you'd like**
A better server implementation(may be use reverse proxy on top of it), to eliminate port mess.

Open to discussion, @exactlyallan

**Comment by jakirkham** [comment]
Are you familiar with [jupyter-server-proxy]( https://jupyter-server-proxy.readthedocs.io/en/latest/ )? This is what Dask uses to solve similar problems. Maybe it would be of use to you here? 🙂

**Comment by AjayThorve** [comment]
Hey @jakirkham , apologies for the delayed response(was on vacation). We are looking into this as a possible solution. Thanks for this!

**Comment by jakirkham** [comment]
No worries. 🙂 Please let me know if you have any questions. 😉
